version: '3.3'

volumes:
  pg_data:
  static:
  media:
  
services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    container_name: foodgram-back
    build: ../backend/
    env_file: ../backend/.env
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    container_name: foodgram-proxy
    build: .
    env_file: ../backend/.env
    ports:
      - 8050:80
    volumes:
      - static:/staticfiles
      - media:/app/media
